BINDIR := ../bin
OBJDIR := o
BINPATH := $(BINDIR)/usearch

CPPFLAGS := $(CPPFLAGS) -DNDEBUG -pthread

CC = ccache gcc
CFLAGS := $(CFLAGS) -O3 -fopenmp -ffast-math -msse -mfpmath=sse

CXX = ccache g++
CXXFLAGS := $(CXXFLAGS) -O3 -fopenmp -ffast-math -msse -mfpmath=sse

UNAME_S := $(shell uname -s)
LDFLAGS := $(LDFLAGS) -O3 -fopenmp -pthread -lpthread
ifeq ($(UNAME_S),Linux)
    LDFLAGS += -static
endif

HDRS = \
  aafreqs.h \
  abdist.h \
  abench.h \
  accepter.h \
  adivmetric.h \
  adivs.h \
  agg.h \
  aligner.h \
  alignresult.h \
  alnheuristics.h \
  alnparams.h \
  alpha.h \
  alphabit.h \
  alphabit_alt.h \
  alphadiv.h \
  alphadivtable.h \
  alphainfo.h \
  alphasig.h \
  annotator.h \
  annotclass.h \
  aspdata.h \
  bbcsearcher.h \
  bdivs.h \
  betadiv.h \
  bitmapsearcher.h \
  bitvec.h \
  bitvec64.h \
  catdict.h \
  cdata.h \
  chainer.h \
  chainer1.h \
  channot.h \
  chimehit.h \
  chunksearcher.h \
  cigar.h \
  classifier.h \
  closedrefsink.h \
  clustersink.h \
  cmd.h \
  cmds.h \
  codeindex.h \
  codeindexsorter.h \
  combo.h \
  constaxf.h \
  constaxsink.h \
  constaxstr.h \
  count.h \
  counters.h \
  countsort.h \
  coveragemap.h \
  crc32.h \
  crosser.h \
  ctest.h \
  dbhitsink.h \
  dbtype.h \
  dectree.h \
  dectreetraindata.h \
  deflate.h \
  deparser.h \
  derep.h \
  derepresult.h \
  detrainer.h \
  diagbox.h \
  diffprofsink.h \
  distmx.h \
  dpband.h \
  dpmem.h \
  duster.h \
  enable_timing.h \
  estats.h \
  evalue.h \
  exactaligner.h \
  exactsearcher.h \
  extendminus.h \
  extendplus.h \
  fastaseqsource.h \
  fastq.h \
  fastqseqsource.h \
  fasttimers.h \
  fasttiming.h \
  fileseqsource.h \
  filetype.h \
  finger.h \
  fragaligner.h \
  genefinder.h \
  getticks.h \
  getu.h \
  globalaligner.h \
  gobuff.h \
  gzguts.h \
  hash.h \
  hitmgr.h \
  hitsink.h \
  hsp.h \
  hspfinder.h \
  inffast.h \
  inffixed.h \
  inflate.h \
  inftrees.h \
  kmerscan.h \
  label.h \
  lcrdata.h \
  linereader.h \
  localaligner.h \
  localaligner2.h \
  lockobj.h \
  lockobjs.h \
  mask.h \
  meanstddev.h \
  merge.h \
  mergeglobals.h \
  mx.h \
  myopts.h \
  myutils.h \
  nofasttiming.h \
  obj.h \
  objmgr.h \
  objtype.h \
  objtypes.h \
  omplock.h \
  onkmer.h \
  orffinder.h \
  otutab.h \
  otutabsink.h \
  outputsink.h \
  pathinfo.h \
  pcb.h \
  pcrsink.h \
  phixfinder.h \
  preston.h \
  prestonsvg.h \
  primes.h \
  profile.h \
  qscoresink.h \
  quarts.h \
  randforest.h \
  recursivesixaligner.h \
  roccer.h \
  rsvalndata.h \
  samout.h \
  samrec.h \
  samseqsource.h \
  searcher.h \
  segmask.h \
  seqdb.h \
  seqdb2.h \
  seqdbsearcher.h \
  seqdbseqsource.h \
  seqhash.h \
  seqinfo.h \
  seqsource.h \
  sign.h \
  sinapssearcher.h \
  sintaxsearcher.h \
  sixaligner.h \
  snvdata.h \
  sort.h \
  sparsemx.h \
  stimers.h \
  strdict.h \
  svg.h \
  svgchart.h \
  syg.h \
  syncmer.h \
  syncmerindex.h \
  tax.h \
  taxbench.h \
  taxsearcher.h \
  taxtree.h \
  taxy.h \
  terminator.h \
  timers.h \
  timing.h \
  tracebit.h \
  tree.h \
  tree2tax.h \
  trees.h \
  tsfeats.h \
  twobit.h \
  uchimefinder.h \
  udbcodedsearcher.h \
  udbdata.h \
  udbfile.h \
  udbparams.h \
  udbsearcher.h \
  udbusortedsearcher.h \
  ufenum.h \
  uncrosser2.h \
  uncrosser2mock.h \
  uparsesink.h \
  upclustersink.h \
  userfields.h \
  uspbag.h \
  uspdata.h \
  ver_counter.h \
  wordcounter.h \
  xdpmem.h \
  xtype.h \
  zconf.h \
  zlib.h \
  zutil.h \

OBJS = \
  $(OBJDIR)/abdist.o \
  $(OBJDIR)/abench.o \
  $(OBJDIR)/abench_fullpctid.o \
  $(OBJDIR)/abench_ga.o \
  $(OBJDIR)/adderrsq.o \
  $(OBJDIR)/alphadivtable.o \
  $(OBJDIR)/alphasig.o \
  $(OBJDIR)/bbcsearcher.o \
  $(OBJDIR)/accepter.o \
  $(OBJDIR)/alphadiv.o \
  $(OBJDIR)/agg.o \
  $(OBJDIR)/alignresult.o \
  $(OBJDIR)/alloc.o \
  $(OBJDIR)/allpairs.o \
  $(OBJDIR)/alnheuristics.o \
  $(OBJDIR)/alnout.o \
  $(OBJDIR)/alnparams.o \
  $(OBJDIR)/alpha.o \
  $(OBJDIR)/alpha2.o \
  $(OBJDIR)/alphadivcmd.o \
  $(OBJDIR)/alphadivrare.o \
  $(OBJDIR)/alphainfo.o \
  $(OBJDIR)/annot.o \
  $(OBJDIR)/annotator.o \
  $(OBJDIR)/arscorer.o \
  $(OBJDIR)/betadiv.o \
  $(OBJDIR)/betadivcmd.o \
  $(OBJDIR)/bimeradp.o \
  $(OBJDIR)/alphabit.o \
  $(OBJDIR)/bitmapsearcher.o \
  $(OBJDIR)/bitvec.o \
  $(OBJDIR)/bitvec64.o \
  $(OBJDIR)/blast6out.o \
  $(OBJDIR)/blosum62.o \
  $(OBJDIR)/cachetest.o \
  $(OBJDIR)/calcdistmx.o \
  $(OBJDIR)/calcdistmxa.o \
  $(OBJDIR)/calcdistmxu.o \
  $(OBJDIR)/catdict.o \
  $(OBJDIR)/cdata.o \
  $(OBJDIR)/chainer1.o \
  $(OBJDIR)/chainer.o \
  $(OBJDIR)/channot.o \
  $(OBJDIR)/chimehit.o \
  $(OBJDIR)/chunksearcher.o \
  $(OBJDIR)/cigar.o \
  $(OBJDIR)/classifier.o \
  $(OBJDIR)/closedrefsink.o \
  $(OBJDIR)/clusteragg.o \
  $(OBJDIR)/clusteraggd.o \
  $(OBJDIR)/clustercc.o \
  $(OBJDIR)/clustercccentroids.o \
  $(OBJDIR)/clusterfast.o \
  $(OBJDIR)/clustersink.o \
  $(OBJDIR)/clustersmallmem.o \
  $(OBJDIR)/cmd.o \
  $(OBJDIR)/cmdline.o \
  $(OBJDIR)/codeindex.o \
  $(OBJDIR)/codeindexsorter.o \
  $(OBJDIR)/codeindexsorter_query.o \
  $(OBJDIR)/comppath.o \
  $(OBJDIR)/constaxf.o \
  $(OBJDIR)/constaxsink.o \
  $(OBJDIR)/constaxstr.o \
  $(OBJDIR)/count.o \
  $(OBJDIR)/countsort.o \
  $(OBJDIR)/countwordsch.o \
  $(OBJDIR)/coveragemap.o \
  $(OBJDIR)/cpubench.o \
  $(OBJDIR)/crosser.o \
  $(OBJDIR)/dbhitsink.o \
  $(OBJDIR)/dectree.o \
  $(OBJDIR)/dectreetraindata.o \
  $(OBJDIR)/deparser.o \
  $(OBJDIR)/derepfull.o \
  $(OBJDIR)/dereppersample.o \
  $(OBJDIR)/derepresult.o \
  $(OBJDIR)/detrainer.o \
  $(OBJDIR)/diagbox.o \
  $(OBJDIR)/diffprofsink.o \
  $(OBJDIR)/distmx.o \
  $(OBJDIR)/distmxsplit.o \
  $(OBJDIR)/drawtree.o \
  $(OBJDIR)/dustmask.o \
  $(OBJDIR)/estats.o \
  $(OBJDIR)/evalue.o \
  $(OBJDIR)/exactaligner.o \
  $(OBJDIR)/exactsearcher.o \
  $(OBJDIR)/extendminus.o \
  $(OBJDIR)/extendminus2.o \
  $(OBJDIR)/extendplus.o \
  $(OBJDIR)/extendplus2.o \
  $(OBJDIR)/fastaexplode.o \
  $(OBJDIR)/fastagetseqsp.o \
  $(OBJDIR)/fastagetseqst.o \
  $(OBJDIR)/fastalettercounts.o \
  $(OBJDIR)/fastaseqsource.o \
  $(OBJDIR)/fasta_xlat.o \
  $(OBJDIR)/fastqfilter2.o \
  $(OBJDIR)/fasttiming.o \
  $(OBJDIR)/fastxadderrs.o \
  $(OBJDIR)/fastqeestats.o \
  $(OBJDIR)/fastqeestats2.o \
  $(OBJDIR)/fastq_sra_splitpairs.o \
  $(OBJDIR)/fastx2qiime.o \
  $(OBJDIR)/fastxdemux.o \
  $(OBJDIR)/fastxgetlabels.o \
  $(OBJDIR)/fastxgetsamplenames.o \
  $(OBJDIR)/fastagetsegs.o \
  $(OBJDIR)/fastxgetseqs.o \
  $(OBJDIR)/fastxgetsubseq.o \
  $(OBJDIR)/fastaindex.o \
  $(OBJDIR)/fastxinfo.o \
  $(OBJDIR)/fastxlearn.o \
  $(OBJDIR)/fastxmasktrack.o \
  $(OBJDIR)/fastxrelabel.o \
  $(OBJDIR)/fastxrevcomp.o \
  $(OBJDIR)/fastxsplit.o \
  $(OBJDIR)/fastxsplitmb.o \
  $(OBJDIR)/fastxsplitn.o \
  $(OBJDIR)/fastxsplitseek.o \
  $(OBJDIR)/fastxstripannots.o \
  $(OBJDIR)/fastxsubsample.o \
  $(OBJDIR)/fastxsyncpairs.o \
  $(OBJDIR)/fastxtrimprimers.o \
  $(OBJDIR)/fastxtruncate.o \
  $(OBJDIR)/fastmask.o \
  $(OBJDIR)/fastq.o \
  $(OBJDIR)/fastqfilter.o \
  $(OBJDIR)/fastqjoin.o \
  $(OBJDIR)/fastqmerge.o \
  $(OBJDIR)/fastqchars.o \
  $(OBJDIR)/fastqseqsource.o \
  $(OBJDIR)/fastauniquesbylabels.o \
  $(OBJDIR)/featureselect1.o \
  $(OBJDIR)/featuretable.o \
  $(OBJDIR)/filetype.o \
  $(OBJDIR)/fileseqsource.o \
  $(OBJDIR)/filterlowc.o \
  $(OBJDIR)/findgene.o \
  $(OBJDIR)/findorfs.o \
  $(OBJDIR)/finger.o \
  $(OBJDIR)/fulldpallpairs.o \
  $(OBJDIR)/genefinder.o \
  $(OBJDIR)/getcc.o \
  $(OBJDIR)/getcmd.o \
  $(OBJDIR)/getfastqs.o \
  $(OBJDIR)/getglobalhsps.o \
  $(OBJDIR)/gethsps.o \
  $(OBJDIR)/gethspsself.o \
  $(OBJDIR)/getsegs.o \
  $(OBJDIR)/gettandemrange1.o \
  $(OBJDIR)/gettandemrange2.o \
  $(OBJDIR)/getu.o \
  $(OBJDIR)/getuniquelettercount.o \
  $(OBJDIR)/globalaligncircle.o \
  $(OBJDIR)/globalaligner.o \
  $(OBJDIR)/globalalignmem.o \
  $(OBJDIR)/gspbag.o \
  $(OBJDIR)/kmerscanbothskip.o \
  $(OBJDIR)/kmerscanskip.o \
  $(OBJDIR)/leila.o \
  $(OBJDIR)/makeglobalchain.o \
  $(OBJDIR)/makesyncmerchains.o \
  $(OBJDIR)/abench_ra.o \
  $(OBJDIR)/palindrome.o \
  $(OBJDIR)/recursivesixaligner.o \
  $(OBJDIR)/gzipfileio.o \
  $(OBJDIR)/hashtime.o \
  $(OBJDIR)/heatmap.o \
  $(OBJDIR)/hitax.o \
  $(OBJDIR)/hitmgr.o \
  $(OBJDIR)/hspfinder.o \
  $(OBJDIR)/interp.o \
  $(OBJDIR)/json.o \
  $(OBJDIR)/kmerscan.o \
  $(OBJDIR)/kmerscanboth.o \
  $(OBJDIR)/randseq.o \
  $(OBJDIR)/rotate.o \
  $(OBJDIR)/selfhsps.o \
  $(OBJDIR)/seqdb2.o \
  $(OBJDIR)/seqdbgetsi2.o \
  $(OBJDIR)/seqhashcircle.o \
  $(OBJDIR)/sixalignallpairs.o \
  $(OBJDIR)/sixalignallpairs2.o \
  $(OBJDIR)/sixalignallpairs3.o \
  $(OBJDIR)/sixlcr.o \
  $(OBJDIR)/sixuclust.o \
  $(OBJDIR)/syg.o \
  $(OBJDIR)/label.o \
  $(OBJDIR)/lcrdata.o \
  $(OBJDIR)/linereader.o \
  $(OBJDIR)/lnfit.o \
  $(OBJDIR)/lnfrac.o \
  $(OBJDIR)/loaddb.o \
  $(OBJDIR)/localaligner.o \
  $(OBJDIR)/localaligner2.o \
  $(OBJDIR)/localmulti.o \
  $(OBJDIR)/lockobj.o \
  $(OBJDIR)/logaln.o \
  $(OBJDIR)/make3way.o \
  $(OBJDIR)/makesearcher.o \
  $(OBJDIR)/makeudb.o \
  $(OBJDIR)/mannwhitney.o \
  $(OBJDIR)/mask.o \
  $(OBJDIR)/maskfastx.o \
  $(OBJDIR)/maxcommonsubseq.o \
  $(OBJDIR)/maxsubseq.o \
  $(OBJDIR)/mergealign.o \
  $(OBJDIR)/mergelogvaln.o \
  $(OBJDIR)/mergepair.o \
  $(OBJDIR)/mergepost.o \
  $(OBJDIR)/mergepre.o \
  $(OBJDIR)/mergestats.o \
  $(OBJDIR)/mergethread.o \
  $(OBJDIR)/mothur.o \
  $(OBJDIR)/mx.o \
  $(OBJDIR)/myutils.o \
  $(OBJDIR)/nastout.o \
  $(OBJDIR)/newick.o \
  $(OBJDIR)/nj.o \
  $(OBJDIR)/njtax.o \
  $(OBJDIR)/objmgr.o \
  $(OBJDIR)/fragaligner.o \
  $(OBJDIR)/omptest.o \
  $(OBJDIR)/orffinder.o \
  $(OBJDIR)/orient.o \
  $(OBJDIR)/otutab.o \
  $(OBJDIR)/otutababdist.o \
  $(OBJDIR)/otutabclassify.o \
  $(OBJDIR)/otutabcore.o \
  $(OBJDIR)/otutabselect.o \
  $(OBJDIR)/otutabsink.o \
  $(OBJDIR)/outputsink.o \
  $(OBJDIR)/outputuc.o \
  $(OBJDIR)/pathinfo.o \
  $(OBJDIR)/pattern.o \
  $(OBJDIR)/pcb.o \
  $(OBJDIR)/pcrsink.o \
  $(OBJDIR)/phix.o \
  $(OBJDIR)/filterphix.o \
  $(OBJDIR)/phixfinder.o \
  $(OBJDIR)/poisson.o \
  $(OBJDIR)/preston.o \
  $(OBJDIR)/prestonsvg2.o \
  $(OBJDIR)/prestonsvg3.o \
  $(OBJDIR)/prime.o \
  $(OBJDIR)/profile.o \
  $(OBJDIR)/qscoresink.o \
  $(OBJDIR)/quarts.o \
  $(OBJDIR)/randforest.o \
  $(OBJDIR)/rcemalloc.o \
  $(OBJDIR)/roccer.o \
  $(OBJDIR)/rsvaln1.o \
  $(OBJDIR)/rsvaln2.o \
  $(OBJDIR)/rsvalndata.o \
  $(OBJDIR)/samfilter.o \
  $(OBJDIR)/samout.o \
  $(OBJDIR)/samrange.o \
  $(OBJDIR)/samrec.o \
  $(OBJDIR)/samseqsource.o \
  $(OBJDIR)/scorepath.o \
  $(OBJDIR)/search.o \
  $(OBJDIR)/searchcmd.o \
  $(OBJDIR)/searcher.o \
  $(OBJDIR)/searchpcr2.o \
  $(OBJDIR)/secant.o \
  $(OBJDIR)/seed.o \
  $(OBJDIR)/segmaskseq.o \
  $(OBJDIR)/seqdb.o \
  $(OBJDIR)/seqdbfromfasta.o \
  $(OBJDIR)/seqdbio.o \
  $(OBJDIR)/seqdbsearcher.o \
  $(OBJDIR)/seqdbseqsource.o \
  $(OBJDIR)/seqhash.o \
  $(OBJDIR)/seqinfo.o \
  $(OBJDIR)/seqsource.o \
  $(OBJDIR)/setnucmx.o \
  $(OBJDIR)/sign.o \
  $(OBJDIR)/sinapssearcher.o \
  $(OBJDIR)/sintaxsummary.o \
  $(OBJDIR)/sintaxsearcher.o \
  $(OBJDIR)/sixaligner.o \
  $(OBJDIR)/sixalignpair.o \
  $(OBJDIR)/sortlen.o \
  $(OBJDIR)/star.o \
  $(OBJDIR)/staralign.o \
  $(OBJDIR)/strdict.o \
  $(OBJDIR)/subsample.o \
  $(OBJDIR)/substmx.o \
  $(OBJDIR)/svg.o \
  $(OBJDIR)/svgchart.o \
  $(OBJDIR)/syncmer.o \
  $(OBJDIR)/syncmerindex.o \
  $(OBJDIR)/syncmerscan.o \
  $(OBJDIR)/syncmerscanboth.o \
  $(OBJDIR)/syncmerscanbothskip.o \
  $(OBJDIR)/syncmerscanskip.o \
  $(OBJDIR)/tabbed2otutab.o \
  $(OBJDIR)/tax.o \
  $(OBJDIR)/taxbench.o \
  $(OBJDIR)/taxclean.o \
  $(OBJDIR)/taxsearcher.o \
  $(OBJDIR)/taxstats.o \
  $(OBJDIR)/taxtree.o \
  $(OBJDIR)/taxtune.o \
  $(OBJDIR)/taxy.o \
  $(OBJDIR)/terminator.o \
  $(OBJDIR)/termmer.o \
  $(OBJDIR)/testglobalalign.o \
  $(OBJDIR)/testsixaligner.o \
  $(OBJDIR)/testsortindexes.o \
  $(OBJDIR)/test_alignerid.o \
  $(OBJDIR)/test_alignerspeed.o \
  $(OBJDIR)/test_recursivealigner.o \
  $(OBJDIR)/test_strat.o \
  $(OBJDIR)/test_syncmerchain.o \
  $(OBJDIR)/test_twobit_decode.o \
  $(OBJDIR)/test_viterbitiming.o \
  $(OBJDIR)/test_viterbitwobitsimple.o \
  $(OBJDIR)/test_viterbitwobit.o \
  $(OBJDIR)/threeway.o \
  $(OBJDIR)/timing.o \
  $(OBJDIR)/tracebackbitmem.o \
  $(OBJDIR)/tree.o \
  $(OBJDIR)/tree2tax.o \
  $(OBJDIR)/treecmp.o \
  $(OBJDIR)/treefromagg.o \
  $(OBJDIR)/treegetdistmx.o \
  $(OBJDIR)/treetab.o \
  $(OBJDIR)/clustertree.o \
  $(OBJDIR)/treetofile.o \
  $(OBJDIR)/trimprimer.o \
  $(OBJDIR)/twobit.o \
  $(OBJDIR)/twobit_decode_ns.o \
  $(OBJDIR)/twobit_encode.o \
  $(OBJDIR)/twobit_kmerscan.o \
  $(OBJDIR)/twobit_kmerscanboth.o \
  $(OBJDIR)/twobit_kmerscanbothskip.o \
  $(OBJDIR)/twobit_kmerscanskip.o \
  $(OBJDIR)/twobit_syncmerscan.o \
  $(OBJDIR)/twobit_syncmerscanboth.o \
  $(OBJDIR)/twobit_syncmerscanbothskip.o \
  $(OBJDIR)/twobit_syncmerscanskip.o \
  $(OBJDIR)/uchime2denovo.o \
  $(OBJDIR)/uchime2ref.o \
  $(OBJDIR)/uchimefinder.o \
  $(OBJDIR)/udbbuild.o \
  $(OBJDIR)/udbusortedsearcherbig.o \
  $(OBJDIR)/udbcodedsearcher.o \
  $(OBJDIR)/udbdata.o \
  $(OBJDIR)/udbinfo.o \
  $(OBJDIR)/udbio.o \
  $(OBJDIR)/udbparams.o \
  $(OBJDIR)/udbsearcher.o \
  $(OBJDIR)/udbstats.o \
  $(OBJDIR)/udbusortedsearcher.o \
  $(OBJDIR)/unbias.o \
  $(OBJDIR)/uncross2.o \
  $(OBJDIR)/uncross2mock.o \
  $(OBJDIR)/ungappedblast.o \
  $(OBJDIR)/unifrac.o \
  $(OBJDIR)/unoise.o \
  $(OBJDIR)/unoise2.o \
  $(OBJDIR)/uparsesink.o \
  $(OBJDIR)/uparsedp.o \
  $(OBJDIR)/uparsepretty.o \
  $(OBJDIR)/upclustersink.o \
  $(OBJDIR)/usearch_main.o \
  $(OBJDIR)/userout.o \
  $(OBJDIR)/viterbiasp.o \
  $(OBJDIR)/viterbifastbandmem.o \
  $(OBJDIR)/viterbifastmem.o \
  $(OBJDIR)/viterbilingap.o \
  $(OBJDIR)/viterbitwobitlingap.o \
  $(OBJDIR)/viterbi_twobit.o \
  $(OBJDIR)/whisker.o \
  $(OBJDIR)/wordcounter.o \
  $(OBJDIR)/wordparams.o \
  $(OBJDIR)/writechhit.o \
  $(OBJDIR)/xdropalignmem.o \
  $(OBJDIR)/xdropbwdmem.o \
  $(OBJDIR)/xdropbwdsplit.o \
  $(OBJDIR)/xdropfwdmem.o \
  $(OBJDIR)/xdropfwdsplit.o \
  $(OBJDIR)/adler32.o \
  $(OBJDIR)/crc32.o \
  $(OBJDIR)/deflate.o \
  $(OBJDIR)/gzlib.o \
  $(OBJDIR)/gzread.o \
  $(OBJDIR)/infback.o \
  $(OBJDIR)/inffast.o \
  $(OBJDIR)/inflate.o \
  $(OBJDIR)/inftrees.o \
  $(OBJDIR)/trees.o \
  $(OBJDIR)/zutil.o \

.PHONY: clean

$(BINPATH) : $(BINDIR)/ $(OBJDIR)/ $(OBJS)
	$(CXX) $(LDFLAGS) $(OBJS) -o $(BINPATH)
	strip -d $(BINPATH)

$(OBJDIR)/ :
	mkdir -p $(OBJDIR)/

$(BINDIR)/ :
	mkdir -p $(BINDIR)/

$(OBJDIR)/%.o : %.c $(HDRS)
	$(CC) $(CPPFLAGS) $(CFLAGS) -c -o $@ $<

$(OBJDIR)/%.o : %.cpp $(HDRS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c -o $@ $<

clean:
	rm -rf $(OBJDIR)/ $(BINPATH)
