name: build_windows

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure and Build
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=amd64 -host_arch=amd64
        IF %ERRORLEVEL% NEQ 0 exit /B %ERRORLEVEL%
        cl /Bv
        set CXX=cl
        set CC=cl
        cmake --preset Win-x64-Release
        IF %ERRORLEVEL% NEQ 0 exit /B %ERRORLEVEL%
        cmake --build --preset windows-release -- -k0
    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
          name: usearch12-windows-binary.exe
          path: ${{ github.workspace }}\out\build\Win-x64-Release\usearch12.exe
          if-no-files-found: error
